############################################################################

branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - JULIA_DEBUG="all"
        - PREDICTMD_OPEN_PLOTS_DURING_TESTS="true"

git:
    depth: 99999999

language: bash

matrix:
    fast_finish: true

notifications:
    email:
        on_failure: always
        on_success: never
os:
    - linux

services:
    - docker

############################################################################

before_install:
    - true
install:
    - true
before_script:
    - true
script:
    - true
after_script:
    - true

############################################################################

stages:
    - "Stage 1 (julia-1: build and test)"
    - "Stage 2 (latex-for-plotting: build and test)"
    - "Stage 3 (offlineregistry: build and test)"
    - "Stage 4 (predictmd: build)"
    - "Stage 5 (predictmd: test `docker-1`)"
    - "Stage 6 (predictmd: test `docker-2`)"
    - "Stage 7 (predictmd: test `docker-3`)"
    - "Stage 8 (predictmd: test `docker-4`)"

############################################################################

jobs:
    include:
        - stage: "Stage 1 (julia-1: build and test)"
          name: "dilumaluthge/julia-1"
          env:
              - IMAGE="julia-1"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/build-and-test.sh
        - stage: "Stage 2 (latex-for-plotting: build and test)"
          name: "dilumaluthge/latex-for-plotting"
          env:
              - IMAGE="latex-for-plotting"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/build-and-test.sh
        - stage: "Stage 3 (offlineregistry: build and test)"
          name: "dilumaluthge/offlineregistry"
          env:
              - IMAGE="offlineregistry"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/build-and-test.sh
        - stage: "Stage 4 (predictmd: build)"
          name: "dilumaluthge/predictmd"
          env:
              - IMAGE="predictmd"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/build.sh
        - stage: "Stage 5 (predictmd: test `docker-1`)"
          name: "dilumaluthge/predictmd"
          env:
              - IMAGE="predictmd"
              - PREDICTMD_TEST_GROUP="docker-1"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/test.sh
        - stage: "Stage 6 (predictmd: test `docker-2`)"
          name: "dilumaluthge/predictmd"
          env:
              - IMAGE="predictmd"
              - PREDICTMD_TEST_GROUP="docker-2"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/test.sh
        - stage: "Stage 7 (predictmd: test `docker-3`)"
          name: "dilumaluthge/predictmd"
          env:
              - IMAGE="predictmd"
              - PREDICTMD_TEST_GROUP="docker-3"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/test.sh
        - stage: "Stage 8 (predictmd: test `docker-4`)"
          name: "dilumaluthge/predictmd"
          env:
              - IMAGE="predictmd"
              - PREDICTMD_TEST_GROUP="docker-4"
          before_install: ./ci/travis/before_install.sh
          script: ./ci/travis/test.sh

############################################################################
