block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    "continuous-integration/travis-ci/push",
]

timeout_sec = 14400

[committer]
name = "aluthge-bors"
email = "bors@aluthge.group"
